Complete "Github Actions" configurations

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,35 @@ on:
       - 'master'
 
 jobs:
+  check:
+    name: Check
+    runs-on: ubuntu-latest
+    steps:
+      - name: 'Checkout'
+        uses: actions/checkout@v4
+      - name: 'Setup Rust'
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          components: rustfmt,clippy
+      - name: 'Check Rust metadata'
+        run: >
+          cargo metadata --format-version=1 --no-deps
+          | jq --compact-output --raw-output '.packages[]'
+          | while read -r package; do
+              if [[ $(echo "$package" | jq --raw-output ".repository") != '${{ github.server_url }}/${{ github.repository }}' ]]; then
+                echo "Package $(echo "$package" | jq '.name') has invalid repository URL $(echo "$package" | jq '.repository')";
+                exit 1;
+              fi
+            done
+      - name: 'Setup Python'
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.13'
+      - name: 'Install pre-commit'
+        run: python -m pip install -U pre-commit
+      - name: 'Run pre-commit'
+        run: pre-commit run --all-files
+
   test:
     name: 'Test'
     runs-on: ${{ matrix.platform.os }}
@@ -78,15 +107,6 @@ jobs:
           components: rustfmt
           target: ${{ matrix.platform.rust_target }}
         if: ${{ !startsWith(matrix.python_version, 'pypy') }}
-      - name: 'Check Rust metadata'
-        run: >
-          [[ $(cargo metadata --format-version=1 --no-deps | jq '.packages[0].repository')
-          == '"${{ github.server_url }}/${{ github.repository }}"' ]]
-        shell: bash
-        if: ${{ !startsWith(matrix.python_version, 'pypy') }}
-      - name: 'Run Rust linter'
-        run: cargo fmt --check
-        if: ${{ !startsWith(matrix.python_version, 'pypy') }}
       - name: 'Run Rust doctests'
         run: rustup run nightly cargo test --doc --target=${{ matrix.platform.rust_target }}
         env:
@@ -109,10 +129,6 @@ jobs:
       - name: 'Install in editable mode'
         run: python -m pip -v install -e '.[tests]'
         if: ${{ startsWith(matrix.python_version, 'pypy') }}
-      - name: 'Install MyPy'
-        run: python -m pip install -U mypy
-      - name: 'Run MyPy'
-        run: python -m mypy ${{ github.event.repository.name }}
       - name: 'Install Python coverage dependencies'
         run: python -m pip install --upgrade coverage[toml]
       - name: 'Run Python doctests'
